name: "Hello World"
description: "Greet someone and record the time"
inputs:
  webhook: # id of input
    description: "webhook"
    required: true
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node16"
  main: "index.js"
