name: "Google Chat Action for Github PR Reviews"
author: "MattNotarangelo"
description: "Github actions for google chat Room Bot"

branding:
  icon: "at-sign"
  color: "green"

inputs:
  webhook:
    description: "Google Chat Webhook URL"
    required: true

runs:
  using: "docker"
  image: "docker://mattnotarangelo/google-chat-action-github-pr-review"
  args:
    - ${{ inputs.webhook }}
