name: "Google Chat Action for Github Pull Request Reviews"
author: "Matt Notarangelo"
description: "Github actions for google chat Room Bot"
branding:
  icon: "at-sign"
  color: "green"
inputs:
  webhook:
    description: "Google Chat Webhook URL"
    required: true

runs:
  using: "node16"
  main: "main.js"
