# name: Send notification to Google chat
# on: [pull_request_review]

# jobs:
#   send_notification:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Google Chat Action for Github Pull Request Reviews
#         uses: MattNotarangelo/PR-review-google-chat-action@v0.0.1
#         with:
#           webhook: "https://chat.googleapis.com/v1/spaces/AAAAsuwCCuQ/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=YIIweNCcTvTmNy0pqJ8og16xtORgfQBTKqlaMEELHPE%3D"

name: Send notification to Google chat
on: [pull_request, pull_request_review]

jobs:       
  send_notification:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Hello world action step
        id: hello
        uses: MattNotarangelo/PR-review-google-chat-action@refs/heads/approval
        with:
          webhook: ${{ secrets.webhook }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
